CREATE TABLE LOG_COMBATE(
  ID_LOG_COMBATE  NUMBER(10) NOT NULL,
  DESAFIANTE NUMBER(10) NOT NULL,
  DESAFIADO NUMBER(10) NOT NULL,
  VENCEDOR NUMBER(10) NOT NULL,
  DURACAO_EM_SEGUNDOS NUMBER(5) NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL,
  ID_COMBATE VARCHAR(160) NOT NULL
);

ALTER TABLE LOG_COMBATE ADD CONSTRAINT DESAFIANTE_FK FOREIGN KEY (DESAFIANTE) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE LOG_COMBATE ADD CONSTRAINT DESAFIADO_FK FOREIGN KEY (DESAFIADO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE LOG_COMBATE ADD CONSTRAINT VENCEDOR_FK FOREIGN KEY (VENCEDOR) REFERENCES USUARIO(ID_USUARIO);


CREATE SEQUENCE "SEQ_LOG_COMBATE";